// <auto-generated />
using System;
using DocMaster.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocMaster.API.Migrations
{
    [DbContext(typeof(DocMasterDbContext))]
    partial class DocMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocMaster.API.Entities.NodeEntity", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Datacenter")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("FreeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("GrpcAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Hot");

                    b.Property<long?>("TotalBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("UptimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkingSetBytes")
                        .HasColumnType("bigint");

                    b.HasKey("NodeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Nodes_Status");

                    b.HasIndex("UpdatedUtc")
                        .HasDatabaseName("IX_Nodes_UpdatedUtc");

                    b.HasIndex("Status", "Tier")
                        .HasDatabaseName("IX_Nodes_Status_Tier");

                    b.ToTable("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
